# Generated by Django 3.2.25 on 2024-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
