# Generated by Django 3.2.25 on 2024-10-21 22:58

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20241021_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=32)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('9am to 12pm', '9am to 12pm'), ('12pm to 3pm', '12pm to 3pm'), ('3pm to 6pm', '3pm to 6pm')], default='9am to 12pm', max_length=12)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.studio')),
            ],
        ),
    ]
