# Generated by Django 3.2.25 on 2024-10-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studiobooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
