# Generated by Django 3.2.25 on 2025-01-18 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20241022_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiobooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
