# Generated by Django 3.2.25 on 2025-01-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_booking_id_studiobooking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiobooking',
            old_name='id',
            new_name='booking_id',
        ),
    ]
